# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75447c53240b9f5ffe6bd13a9d483fce5ac7c4ce7977ffe4f60e50d119d7f41ce51749f248ce15d52b0facca23be2d99f50baf6f8b74879896118fe07218bb02

test:
  secret_key_base: 70fd79984164c19e46dfe1679485d517fe453c34b6b9575b0df1869eec3566256ff70ec0a3076588dc508a22dc404805cfa2acb7d4ca29a748eb85d98000b521

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
