branding: false
image_caption: true
skin: blueskin
height: 250
media_live_embeds: true

toolbar:
  - styleselect | bold italic | undo redo || forecolor | backcolor| image | media | link | emoticons | preview | fullscreen
plugins:
  - image
  - link
  - emoticons
  - preview
  - textcolor
  - media
  - fullscreen
