db:
  image: onjin/alpine-postgres:9.5
  ports:
    - "5433:5432"
  environment:
    POSTGRES_USER: root
web:
  build: .
  volumes:
    - .:/thredded
  working_dir: /thredded
  environment:
    DB: postgresql
    DB_USERNAME: root
    DB_PASSWORD:
  command: >
    bash -c 'script/wait-for-tcp $THREDDED_DB_1_PORT_5432_TCP_ADDR $THREDDED_DB_1_PORT_5432_TCP_PORT &&
             rake db:drop db:create db:migrate db:seed &&
             rake dev:server'
  ports:
    - "9292:9292"
  links:
    - db
